### ISSUE TITLE
bug with CC.C in NEG

### ISSUE THREAD

**Issue by manfreda-dot-org** [spc476/mc6809#4]
The C bit is set incorrectly

original
```
static mc6809byte__t op_neg(mc6809__t *cpu,mc6809byte__t const src)
{
  mc6809byte__t res;
  
  assert(cpu != NULL);
  
  res       = -src;
  cpu->cc.n = (res >  0x7F);
  cpu->cc.z = (res == 0x00);
  cpu->cc.v = (src == 0x80);
  cpu->cc.c = (src >  0x7F);
  return res;
}
```

fixed
```
static mc6809byte__t op_neg(mc6809__t *cpu,mc6809byte__t const src)
{
  mc6809byte__t res;
  
  assert(cpu != NULL);
  
  res       = -src;
  cpu->cc.n = (res >  0x7F);
  cpu->cc.z = (res == 0x00);
  cpu->cc.v = (src == 0x80);
  cpu->cc.c = (src != 0x00);
  return res;
}```

**Comment by spc476** [comment]
I'm not convinced that's the right fix. All I can find about this is the following:

> The C (carry) bit represents a borrow and is set to the inverse of the resulting binary carry.  Note that $80 is replaced by itself and only in this case is the V (overflow) bit set.  The value 00 is also replaced by itself, and only in this case is the C (carry) bit cleared.

(From the EDTASM+ manual for the Color Computer)

I looked at the source code for another 6809 emulator I have, and what it does is basically (and I"m not sure if this is correct either):

    int r = -reg;
    cf = (r & 0x100) >> 8;

I don't have ready access to my actual 6809 system (it's in storage) so I can't run exhaustive tests on this at this time.  Do you have an actual 6809 to test against?

**Comment by spc476** [comment]
Nevermind my previous message (since deleted).  I ran the following code to test the CC between `NEGA` and "0-A" to test the original code and your proposed fix:

    main            clra
                    clrb
                    lds     #$8000
    mainloop        bsr     testneg
                    decb
                    tfr     b,a
                    bne     mainloop
                    
                    fcb     5
                    
    testneg         sta     ,-s
                    nega
                    pshs    cc
                    clra
                    suba    1,s
                    pshs    cc
                    
                    lda     1,s
                    anda    #1
                    sta     1,s
                    lda     ,s+
                    anda    #1
                    cmpa    ,s+
                    bne     tn_bad1
                    lda     ,s+
                    rts
                    
    tn_bad1         fcb     1

Yup, you were correct with your fix.

**Comment by manfreda-dot-org** [comment]
FWIW I found this

http://www.coco3.com/community/wp-content/uploads/2010/03/6x09_Instruction_Sets.pdf


On NEG it states
  C The Carry flag is cleared if the original value was 0; set otherwise.

In answer to your other question, I don't have a 6809  but I am writing an
emulator for a game which runs on the 6809, so that's just about as good.
The gameplay had various bugs which is how I found the issues I've posted.
As I've fixed the issues the game got progressively more stable.

The NEG bug was the last issue -- after fixing it on my end the gameplay
worked flawlessly.  So I'm pretty sure this is the last issue.

**Comment by spc476** [comment]
What a great document.  

Now I'm curious---what made you choose this project instead of another one, like MAME?

**Comment by manfreda-dot-org** [comment]
Well back in the 90's I wrote a fast 6809 emu in assembly.  I still have the original 1998 object file, but the source is lost.  Used the object on a few projects since then by linking it into a DLL.  That's what I wanted to use here.  I knew it worked and I knew the programming model.  Debugging these things is a real pain, and I didn't want to have to start from scratch.

My object was compiled in fastcall mode, and C# doesn't like fastcall it seems. After several days of twiddling I was unable to get it to work properly in C# without crashing   So I decided to look around for a quick and dirty 6809.   I really wanted a minimalist emulator, no bells and whistles, as speed is my primary goal.

The MAME 6809 is written around the MAME model, its in CPP and has a built in disassembler, other 68xx modes, other links into the MAME architecture.  I didn't want to have to "carve" what I needed out of the project.  Would have been too messy.

I basically searched github for 6809 emulators.  There are a few dozen there. There were a bunch with built in debuggers, GUI features, or written in CPP with an object hierarchy, or written in a way that looked really inefficient, features I didn't need, etc. 

Your emu struck me as a pretty clean/minimalist implementation.  No bells/whistles.  Written in C and the API was simple. Not many outside hooks - it is mostly self contained. You had common routines shared by the opcodes, which meant I would have a fighting chance of debugging it if it came to that.  Your I/O model was straightforward and wouldn't take much for me to adapt to my needs.  So I gave it a shot.

I actually got it running pretty quickly.  I made some changes so it would work better with my I/O model.  Hope you don't have a problem with that.  I've posted the modified source in my project with your original license

Apart from the few bugs I found it's working great!  Thanks!

**Comment by spc476** [comment]
I have no issues with you changing the code (and I'm amazed at the changes---it was way more than I expected).  I'm glad you found it useful and I hope the bugs didn't cause too much of a headache.  I'm also surprised that I,Robot used a 6809 in it.  Very neat.
